# The Boinc project values, you need to fill in your own account key.
# You can also change the project if you wish to use resources for something
# else than lhcathome.
boinc:
  project: https://lhcathome.cern.ch/lhcathome/
  accountKey: fill-this-with-your-own-account-uuid
  # Resources for boinc pods. This depends on the type of jobs being run.
  # These high number are currently for ATLAS jobs.
  cpu: "6.5"
  memory: "12G"

# A set of predefined priorities for your cluster.
# If you can drop if you already manage priorities yourself, otherwise this
# will setup a default one and a very low priority which is used by the boinc
# workloads (enabling preemption).
priority:
  - name: default-priority
    value: 100000
    default: true
  - name: vlow-priority
    value: 0

# Boinc horizontal pod auto scaler configuration. The goal is to backfill the
# cluster with boinc workloads, so we use an hpa resource with a very high
# number of max replicas (max replicas is currently mandatory).
# Set the targetCPU so that it won't fill the cluster completely, leaving
# margin for preempting boinc pods while scaling up higher priority
# applications.
hpa:
  minReplicas: 1
  maxReplicas: 10000000
  targetCPU: 80
  priority: vlow-priority

# We need cvmfs available for ATLAS workloads, with these repos configuraed.
cvmfs:
  repo:
    - atlas
    - atlas-condb
    - sft

# A sample deployment to see the pod auto scaling working nicely, it deploys
# higher prio pods consuming a lot of cpu.
highpriodemo:
  enabled: true
  replicas: 1
  cpu: "1"
  memory: "1G"
