# The Boinc project values, you need to fill in your own account key.
# You can also change the project if you wish to use resources for something
# else than lhcathome.
boinc:
  project: https://lhcathome.cern.ch/lhcathome/
#  project: http://setiathome.berkeley.edu/
  accountKey: fill-this-with-your-own-account-uuid
  requests:
    cpu: "1000m"
    memory: "64Mi"
  limits:
    cpu: "2000m"
    memory: "64Mi"
  # Uncomment the line below if running ATLAS jobs (SLC6 based client image)
  # image: gitlab-registry.cern.ch/cloud/boinc-client
  #
  # Resources for boinc pods. This depends on the type of jobs being run.
  # These high number are currently for ATLAS jobs.

# A set of predefined priorities for your cluster.
# If you can drop if you already manage priorities yourself, otherwise this
# will setup a default one and a very low priority which is used by the boinc
# workloads (enabling preemption).
priority:
  - name: default-priority
    value: 100000
    default: true
  - name: vlow-priority
    value: -100000

# Boinc horizontal pod auto scaler configuration. The goal is to backfill the
# cluster with boinc workloads, so we use an hpa resource with a very high
# number of max replicas (max replicas is currently mandatory).
#
# vlow-priority should be set to < -10, so that the cluster auto-scaler does
# not take them into account.
hpa:
  minReplicas: 1
  maxReplicas: 10000000
  targetCPU: 80
  priority: vlow-priority

# We need cvmfs available for ATLAS workloads, with these repos configured.
cvmfs:
  repo:
#    - atlas
#    - atlas-condb
#    - sft

# A sample deployment to see the pod auto scaling working nicely, it deploys
# higher prio pods consuming a lot of cpu.
highpriodemo:
  enabled: false
  replicas: 1
  cpu: "1000m"
  memory: "256Mi"
